// app/layout.jsx
import "./globals.css";

export const metadata = {
  title: "Sales Dashboard",
  description: "Generated by Next.js + Supabase",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* 
        Optionally, add some global Tailwind classes to <body>
        e.g. <body className="bg-gray-50 text-gray-900">
      */}
      <body>
        {children}
      </body>
    </html>
  );
}
